<div class="container main">
    <div class="row">
        <div class="col-md-9">
            <h1>Trustees</h1>
            <h2>S H Raza</h2>
            <p>Born in 1922, Babaria (Madhya Pradesh), Raza graduated from Sir J.J. School of Arts, Mumbai in 1943 and became one of the founding members of Progressive Artists Group in 1947. He received the French Government Scholarship in 1950 to study at Ecole Nationale des Beaux-Arts in Paris. In his long career, Raza has held several solo and group exhibitions in India and abroad which include Biennale de Venice, 1956; Biennale de Menton, 1964, 66, 68, 72 & 76; Biennale du Moroc, Rabat, 1963; Biennale, Bharat Bhavan, Bhopal, 1986; Biennial of Havana, 1987; Jane Woorhese Zimmerli Art Museum, New Jersey, 2002; Swasti, NGMA, New Delhi, 2007. Several publications have been released on his life and work which include Bindu: Space and Time in Raza’s Vision by Geeti Sen, 1997; Raza by Ashok Vajpeyi, 2002 and A Life in Art: Raza written & edited by Ashok Vajpeyi, 2007. He is a recipient of Prix de la Critique (Paris, 1956); the Rajkeeya Samman and Kalidas Samman (Government of Madhya Pradesh, 1978 & 1997); and Officier de LOrdre Des Arts et des Lettres (Government of France, 2002). The Government of India conferred him with the Padma Shri in 1981 and the Padma Bhushan in 2007. He was also honoured with the Fellowship of the Lalit Kala Akademi in 1983. After sixty years of living in France Raza returned to India in December 2010 and now lives and works in New Delhi.</p>
            <h2>Ashok Vajpeyi</h2>
            <p>Ashok Vajpeyi, a Hindi poet-critic, translator, editor and culture-activist, is a major cultural figure of India. He is widely recognised as an outstanding promoter of culture and an innovative institution builder. </p>
            <p>As an organiser he has more than a thousand events relating to literature, music, dances, theatre, visual arts, folk and tribal arts, cinema, etc., to his credit. He set up the renowned multi-arts centre, Bharat Bhavan, in Bhopal, and has been the first Vice-Chancellor of the Mahatma Gandhi International Hindi University (set up by Government of India). For more than a year he doubled up as the Director General of the National Museum, New Delhi and as the Vice-Chairman, National Museum of Man, Bhopal. A prominent public intellectual of India, he has been a creative global trotter and has visited Europe many times to attend conferences, deliver lectures and give readings. Mr. Vajpeyi has been a Writer in-Residence at Jamia Millia Islamia University and a Fellow of K.K Birla Foundation. He has been decorated by the President of the Republic of Poland with the Polish National Award. The Officer’s Cross of Merit of the Republic of Poland; by the French Government’s award of ‘Officier De L’Ordre Des Arts Et Des Lettres,’ and the Embassy of Romania to India’s award ‘Best Promoter of Indo-Romanian Relations.’ In India he has been awarded the Sahitya Akademi Award, the Dayawati Kavi Shekhar Samman and the Kabir Samman. Mr. Vajpeyi recently retired as Chairman, Lalit Kala Akademi, Ministry of Culture, Government of India, New Delhi. He lives in Delhi.</p>
            <h2>Arun Vadehra</h2>
            <p>A graduate in mathematics from St. Stephen’s College in New Delhi, Arun Vadehra was already established in the construction business when he decided to open Vadehra Art Gallery (VAG) in Delhi in 1987, at a time in India when art was not taken seriously by the public at large. Over the past twenty-five years, VAG has promoted contemporary Indian and international art through exhibitions, retrospectives, publications and educational programmes, and has become the locus through which the works of both modern and contemporary artists reach the public. Having worked with some of the finest contemporary Indian artists over the years, since 2006, VAG has been broadening its programme to hold exhibitions by international artists. Exhibitions of established artists like Pablo Picasso, Francis Bacon, Lucian Freud, Bernd and Hilla Becher, and most recently a major exhibition of Yoko Ono, have been held at the Gallery. Its goal is to be a vibrant art institution that brings audiences here in contact with the best of contemporary art from within and outside India. Arun Vadehra’s sustained efforts in bringing Indian art to the notice of the international art market led to Christie’s holding regular auctions of modern Indian art starting in 1995. As the consultant to Christie’s for Indian contemporary art, he has been actively involved in organizing annual auctions in London, New York, Dubai and Hong Kong, among other cities.</p>
        </div>
        <div class="col-md-3 sidebar">
<?php require_once('application/views/generalSidebar.php');?>
        </div>
    </div>
</div>
