<div class="container main">
    <div class="row">
        <div class="col-md-9">
            <h1>S H Raza</h1>
            <h2>22 February 1922 &ndash; 23 July 2016</h2>
            <p>Sayed Haider Raza was one of India’s greatest icons of modern and contemporary art. A founder of the enormously influential Progressive Artists group, he combined western abstraction with Indian visual traditions and helped to create a uniquely Indian style of contemporary art.</p>
            <h2>Education</h2>
            <p>S. H. Raza was born in Babaria, Madhya Pradesh on 22 February 1922. He finished high school from Damoh in Madhya Pradesh and then enrolled in the Nagpur School of Arts where he studied art until 1943 when he was awarded a scholarship to attend the Sir J. J. School of Art in Bombay. In 1950 Mr. Raza went to Paris on a 2years French government scholarship to study at the Ecole Nationale Superieure des Beaux-Arts in Paris.</p>
            <h2>Career</h2>
            <p>In 1946, Mr. Raza held his first solo show at the Bombay Art Society Salon. In 1947, he cofounded the Progressive Artists group in Bombay, along with other artists including F. N. Souza and K. N. Ara. The group set out to break free from the influences of European realism in Indian art and bring an Indian inner vision (antar gyan) into Indian art. The group had its first show in 1948, shortly before Mr. Raza left for France. After completing his studies at the Ecole Nationale Superieure des Beaux-Arts, he travelled across Europe and then settled down in Paris where he lived and exhibited his work until 2010 when he moved back to India.</p>
            <p>Once in France, Raza continued to experiment with currents of western modernism, moving from expressionist modes towards greater abstraction and eventually incorporating elements of tantric visual forms from Indian scriptures. Whereas his fellow contemporaries dealt with more figural subjects, Raza chose to focus on landscapes in the 1940s and 50s, inspired in part by the move to France. One of his significant works during his early Paris years is “Village with Church”(1958). He became the first non-French artist to be awarded the prestigious Prix de la Critique in 1956. Over time he moved from the expressionist mode towards greater abstraction and began to incorporate an Indian vision and Indian ethnography into his works. Numerous visits to India and an urge to forge a new artistic direction brought forth the abstract concept of Bindu which, according to him, is the center of creation and existence. After the introduction of Bindu he added newer dimensions to his thematic oeuvre in the following decades. With the inclusion of themes around the Tribhuj (Triangle), which visualized the Indian concepts of space and time, as well as that of prakriti-purusha (the female and the male energy), his transformation from an expressionist to a master of abstraction, was complete.</p>
            <p>In his long career, Raza has held several solo and group exhibitions in India and abroad. Some of the exhibitions include Biennale de Venice, 1956; Biennale de Menton, 1964, 66, 68, 72 & 76; Biennale du Moroc, Rabat, 1963; Biennale, Bharat Bhavan, Bhopal, 1986; Bienniale of Havana, 1987; Jane Woorhese Zimmerli Art Museum, New Jersey, 2002; Swasti, NGMA, New Delhi, 2007. His important works include Saurashtra, Shanti Bindu, La Terre and Gestation.</p>
            <h2>Social Contributions</h2>
            <p>Even when he was living in France Raza always felt deeply concerned about the struggles of young Indian artists and the inadequate opportunities for them to achieve their full potential. On his almost annual sojourns to India, he would always find time and energy to meet young artists and see and discuss their works. He never forgot the hard times he and other artist (M. F. Husain, F. N. Souza, H. A. Gade, S. K. Bakre and Krishnaji Ara) had when they were young and putting together the path-breaking Progressive Artists Group.</p>
            <p>In 2001, Raza created the Raza Foundation to support young artists in India. It began by granting awards to promising Indian artists, beginning with two awards annually, one in visual arts and one in poetry. The awards were later expanded to cover classical music and classical dance as well. Each award carries a sum of Rs. one lakh and a citation. Some of the best, the most innovative and daring artists, poets, musicians and dancers have been recipients of these highly coveted and prestigious awards.</p>
            <h2>Awards and Recognitions</h2>
            <p>The government of India recognized the contributions of Raza Sahab by conferring on him the Padma Shri in 1981, the Padma Bhushan in 2007 and the Padma Vibhushan in 2013. He was a recipient of Prix de la Critique (1956); the Rajkeeya Samman and Kalidas Samman (Government of Madhya Pradesh, 1978 & 1997); he was a Fellow of the Lalit Kala Akademi and Officier de L’Ordre Des Arts et des Lettres (Government of France, 2002). In 1962, he became a visiting lecturer at the University of California in Berkeley. In 2015 he was conferred the highest French civilian honour, the Commandeur de la Legion d'honneur (Commander of the Legion of Honour). He was awarded D.Lit (Hanoris Causa) by Indira Kala Sangeet Vishwavidyalaya, Khairagarh, Chhatisgarh (2014) and Shiv Nadar University, Greater Noida, Uttar Pradesh (2015).</p>
        </div>
        <div class="col-md-3 sidebar">
<?php require_once('application/views/generalSidebar.php');?>
        </div>
    </div>
</div>
